import type { Metadata } from 'next'
import '@src/styles/global.css'
import React from 'react'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const RootLayout = ({ children }: { children: React.ReactNode }) => {
    return (
        <html lang='en'>
            <body className='bg-black'>{children}</body>
        </html>
    )
}
export default RootLayout
