import type { Metadata } from 'next'
import '@src/styles/global.css'
import { ReactNode } from 'react'
import Toast from '@src/components/ui/toast'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const RootLayout = ({ children }: { children: ReactNode }) => {
    return (
        <html lang='en'>
            <body className='bg-black'>
                <main>
                    {children}
                    <Toast />
                </main>
            </body>
        </html>
    )
}
export default RootLayout
